### ISSUE TITLE
packagingOptions does not work with com.android.tools.build:gradle:3.3.0

### ISSUE THREAD

**Issue by dschuermann** [jedrivisser/private_libraries#1]
Hey @jedrivisser . Thanks for this example!

Do you know how to get the exclusion via packagingOptions working on Android Gradle Plugin > 3?

I am using "com.android.tools.build:gradle:3.3.0" and it no longer excludes the files defined via packagingOptions.

**Comment by jedrivisser** [comment]
Will have a look

**Comment by jedrivisser** [comment]
I cannot get it to work. I think it is supposed to work by default according to the [gradleDSL](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html):

`/META-INF/maven/** (all files in the maven meta inf directory)` is excluded by default since 3.0.0

I tried just pasting the jars in the libs folder and using `implementation fileTree(dir: 'libs', include: ['*.jar'])`. This gave the same problem though.

If you find anything, please let me know

**Comment by jedrivisser** [comment]
It is proguard/R8 doing the repackaging and adding those files to the aar.

DexGuard handles it correctly and throws away all the metadata. Though it is not possible for most people to use

**Comment by dschuermann** [comment]
Thanks for reproducing. I reached to the same conclusion and opened https://issuetracker.google.com/issues/124858507 (though I messed up the title).

For now I use a local jar and removed some files manually from this jar.

**Comment by jedrivisser** [comment]
Tested with `com.android.tools.build:gradle:3.5.0-alpha10` and looks like it is working.

Do not need the excludes, the maven folder is excluded by default. I think they are excluding what is stated in the docs now: https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html

Pushed working code to the `update` branch.  Will merge to master when it is in a stable release
